### ISSUE TITLE
Swagger errors in API Reference Repository

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-api-reference#188]
https://jira.commercetools.com/browse/SUPPORT-10510

**Comment by nspeet** [comment]
Hi @ashishhk Ran the api.swagger3.json through open api 3.0 validator. Saw the following issues: 
1. Token trait_query_ not found. This var may need to be adjusted in its definition/usage
2.Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/components/responses/trait_conflicting_409
    Missing required property: $ref at #/components/responses/trait_conflicting_409
    Data does not match any schemas from 'oneOf' at #/components/responses/trait_conflicting_409/content/application/json/schema
      Additional properties not allowed: includePath at #/content/application/json/schema
      Missing required property: $ref at #/content/application/json/schema
3. See other issues that were reported on SUPPORT-10510

How is this file being created? Can someone regenerate it this week? Or go through and make adjustments for each issue above?

**Comment by nspeet** [comment]
@ashishhk which developer is best to discuss this with? We are blocked by this issue.

**Comment by ashishhk** [comment]
Hello @nspeet @jenschude  should be able to help you after tomorrow.

**Comment by jenschude** [comment]
I optimized the conversion step by first expanding the RAML files before doing the actual conversion and afterwards fixing some smaller issues due to and tooling issue. The build now validates the generated swagger files. See:

https://github.com/commercetools/commercetools-api-reference/runs/1389621549?check_suite_focus=true#step:7:83

https://github.com/commercetools/commercetools-api-reference/runs/1389621549?check_suite_focus=true#step:7:88
